// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComBrw76roBb3G2mYpzEIevRSJyrxq_eI',
    appId: '1:473371050913:web:238821f5ae76d1e2ecc1e0',
    messagingSenderId: '473371050913',
    projectId: 'shesos-v1',
    authDomain: 'shesos-v1.firebaseapp.com',
    storageBucket: 'shesos-v1.firebasestorage.app',
    measurementId: 'G-1MG5YYZK3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADfB2Z-0QZJfI65-tVZpi6DJW4nF2pyXE',
    appId: '1:473371050913:android:6d8646d642b833afecc1e0',
    messagingSenderId: '473371050913',
    projectId: 'shesos-v1',
    storageBucket: 'shesos-v1.firebasestorage.app',
  );
}
